//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""e9e173a9-c5e1-47a6-9ef4-e44f7cddfaf5"",
            ""actions"": [
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""bd030fd2-f12b-460d-b7a5-27776cc64d2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""1160c799-ae4a-437e-9f20-9b9fb2aa9cee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""9c1fa335-9bad-4bbe-8581-3b6b56bd3a34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""1e8cc9b0-abb0-4c72-a33d-87b0de019914"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""86472662-0b61-4972-9bd1-b2c99c78422e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""948ca20c-048f-42e3-ac15-39f4372cd3c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""23dc0b9c-7eb5-42f8-a297-f772b8f5d588"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""7becafef-d0ad-4d72-a4f9-c3d29fb75d03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""ccfdb9ca-6b8b-4040-8ec3-3c15a9491e36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""36c0a98b-07de-4314-9c52-fee7a31d68e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Plus"",
                    ""type"": ""Button"",
                    ""id"": ""fd3c5525-cced-4939-98bf-4e2c96039e98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Minus"",
                    ""type"": ""Button"",
                    ""id"": ""6b0ea9f6-bc00-4ed1-b47f-7ed279905fba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Multiply"",
                    ""type"": ""Button"",
                    ""id"": ""994cdecb-8e3d-4674-820a-cb9124af99f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Divide"",
                    ""type"": ""Button"",
                    ""id"": ""16c8572e-db60-4a72-85c1-cfabcd00106e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clear"",
                    ""type"": ""Button"",
                    ""id"": ""ff3b1430-8c93-4daa-9241-41f8222bb784"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8590681c-d035-4efa-a41a-4b51ac959d3d"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ff61971-771b-4a7f-b493-04e635cd32bf"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""226d93b5-c6f9-4f61-8086-8b0ac35fdde1"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed9edb46-20e6-41b3-bf36-cdf80116051f"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99f92101-bd43-4325-a717-6093eef25344"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5925ccc9-b59f-4949-97c4-fa9ee78379e1"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9e77454-2d16-4774-b36d-d1611bcfc3dc"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4332e314-14e8-4b39-a591-2d5b81f69061"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00d658fe-b636-4289-bf21-40ae1a080eec"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3a5478e-ad8b-49ad-bf05-395067bc11f6"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4870a8ce-2676-459e-8aaf-74adcbfa1e5a"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Plus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34ce5cd9-9c9b-41e6-9294-ebeb091b9f59"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Minus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f86ee4c-dfb6-451f-9643-62f0c938dd01"",
                    ""path"": ""<Keyboard>/numpadMultiply"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Multiply"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30358bf1-f5a9-4164-9abd-f0b348a1b804"",
                    ""path"": ""<Keyboard>/numpadDivide"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Divide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d0e4cb6-813e-4b03-a54d-af82084071f3"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Normal"",
                    ""action"": ""Clear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Normal"",
            ""bindingGroup"": ""Normal"",
            ""devices"": []
        }
    ]
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_One = m_Default.FindAction("One", throwIfNotFound: true);
        m_Default_Two = m_Default.FindAction("Two", throwIfNotFound: true);
        m_Default_Three = m_Default.FindAction("Three", throwIfNotFound: true);
        m_Default_Four = m_Default.FindAction("Four", throwIfNotFound: true);
        m_Default_Five = m_Default.FindAction("Five", throwIfNotFound: true);
        m_Default_Six = m_Default.FindAction("Six", throwIfNotFound: true);
        m_Default_Seven = m_Default.FindAction("Seven", throwIfNotFound: true);
        m_Default_Eight = m_Default.FindAction("Eight", throwIfNotFound: true);
        m_Default_Nine = m_Default.FindAction("Nine", throwIfNotFound: true);
        m_Default_Zero = m_Default.FindAction("Zero", throwIfNotFound: true);
        m_Default_Plus = m_Default.FindAction("Plus", throwIfNotFound: true);
        m_Default_Minus = m_Default.FindAction("Minus", throwIfNotFound: true);
        m_Default_Multiply = m_Default.FindAction("Multiply", throwIfNotFound: true);
        m_Default_Divide = m_Default.FindAction("Divide", throwIfNotFound: true);
        m_Default_Clear = m_Default.FindAction("Clear", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_One;
    private readonly InputAction m_Default_Two;
    private readonly InputAction m_Default_Three;
    private readonly InputAction m_Default_Four;
    private readonly InputAction m_Default_Five;
    private readonly InputAction m_Default_Six;
    private readonly InputAction m_Default_Seven;
    private readonly InputAction m_Default_Eight;
    private readonly InputAction m_Default_Nine;
    private readonly InputAction m_Default_Zero;
    private readonly InputAction m_Default_Plus;
    private readonly InputAction m_Default_Minus;
    private readonly InputAction m_Default_Multiply;
    private readonly InputAction m_Default_Divide;
    private readonly InputAction m_Default_Clear;
    public struct DefaultActions
    {
        private @Inputs m_Wrapper;
        public DefaultActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @One => m_Wrapper.m_Default_One;
        public InputAction @Two => m_Wrapper.m_Default_Two;
        public InputAction @Three => m_Wrapper.m_Default_Three;
        public InputAction @Four => m_Wrapper.m_Default_Four;
        public InputAction @Five => m_Wrapper.m_Default_Five;
        public InputAction @Six => m_Wrapper.m_Default_Six;
        public InputAction @Seven => m_Wrapper.m_Default_Seven;
        public InputAction @Eight => m_Wrapper.m_Default_Eight;
        public InputAction @Nine => m_Wrapper.m_Default_Nine;
        public InputAction @Zero => m_Wrapper.m_Default_Zero;
        public InputAction @Plus => m_Wrapper.m_Default_Plus;
        public InputAction @Minus => m_Wrapper.m_Default_Minus;
        public InputAction @Multiply => m_Wrapper.m_Default_Multiply;
        public InputAction @Divide => m_Wrapper.m_Default_Divide;
        public InputAction @Clear => m_Wrapper.m_Default_Clear;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
            @Plus.started += instance.OnPlus;
            @Plus.performed += instance.OnPlus;
            @Plus.canceled += instance.OnPlus;
            @Minus.started += instance.OnMinus;
            @Minus.performed += instance.OnMinus;
            @Minus.canceled += instance.OnMinus;
            @Multiply.started += instance.OnMultiply;
            @Multiply.performed += instance.OnMultiply;
            @Multiply.canceled += instance.OnMultiply;
            @Divide.started += instance.OnDivide;
            @Divide.performed += instance.OnDivide;
            @Divide.canceled += instance.OnDivide;
            @Clear.started += instance.OnClear;
            @Clear.performed += instance.OnClear;
            @Clear.canceled += instance.OnClear;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
            @Plus.started -= instance.OnPlus;
            @Plus.performed -= instance.OnPlus;
            @Plus.canceled -= instance.OnPlus;
            @Minus.started -= instance.OnMinus;
            @Minus.performed -= instance.OnMinus;
            @Minus.canceled -= instance.OnMinus;
            @Multiply.started -= instance.OnMultiply;
            @Multiply.performed -= instance.OnMultiply;
            @Multiply.canceled -= instance.OnMultiply;
            @Divide.started -= instance.OnDivide;
            @Divide.performed -= instance.OnDivide;
            @Divide.canceled -= instance.OnDivide;
            @Clear.started -= instance.OnClear;
            @Clear.performed -= instance.OnClear;
            @Clear.canceled -= instance.OnClear;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    private int m_NormalSchemeIndex = -1;
    public InputControlScheme NormalScheme
    {
        get
        {
            if (m_NormalSchemeIndex == -1) m_NormalSchemeIndex = asset.FindControlSchemeIndex("Normal");
            return asset.controlSchemes[m_NormalSchemeIndex];
        }
    }
    public interface IDefaultActions
    {
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
        void OnPlus(InputAction.CallbackContext context);
        void OnMinus(InputAction.CallbackContext context);
        void OnMultiply(InputAction.CallbackContext context);
        void OnDivide(InputAction.CallbackContext context);
        void OnClear(InputAction.CallbackContext context);
    }
}
